
// This file has been generated by the GUI designer. Do not modify.
namespace SDVMMR
{
	public partial class Setting
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label GeneralSettings;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label SteamFolderLabel;

		private global::Gtk.Entry SteamFolderBox;

		private global::Gtk.Button SteamFolderTN;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label GameFolderLabel;

		private global::Gtk.Entry GameFolderBox;

		private global::Gtk.Button GameFolderBtn;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label GogLabel;

		private global::Gtk.Entry GogBox;

		private global::Gtk.Button GogCBtn;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label LanguageLabel;

		private global::Gtk.ComboBox LanguageBox;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Label ModSettings;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.HBox hbox6;

		private global::Gtk.CheckButton overwriteButton;

		private global::Gtk.HSeparator hseparator4;

		private global::Gtk.Label SteamSettings;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button SetVDF;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button Save;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SDVMMR.Setting
			this.Name = "SDVMMR.Setting";
			this.Title = global::Mono.Unix.Catalog.GetString("Setting");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(12));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child SDVMMR.Setting.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GeneralSettings = new global::Gtk.Label();
			this.GeneralSettings.Name = "GeneralSettings";
			this.GeneralSettings.Ypad = 6;
			this.GeneralSettings.LabelProp = global::Mono.Unix.Catalog.GetString("<b>General Settings</b>");
			this.GeneralSettings.UseMarkup = true;
			this.vbox2.Add(this.GeneralSettings);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GeneralSettings]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SteamFolderLabel = new global::Gtk.Label();
			this.SteamFolderLabel.WidthRequest = 80;
			this.SteamFolderLabel.Name = "SteamFolderLabel";
			this.SteamFolderLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Steam folder");
			this.hbox2.Add(this.SteamFolderLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SteamFolderLabel]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SteamFolderBox = new global::Gtk.Entry();
			this.SteamFolderBox.CanFocus = true;
			this.SteamFolderBox.Name = "SteamFolderBox";
			this.SteamFolderBox.IsEditable = true;
			this.SteamFolderBox.InvisibleChar = '●';
			this.hbox2.Add(this.SteamFolderBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SteamFolderBox]));
			w4.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.SteamFolderTN = new global::Gtk.Button();
			this.SteamFolderTN.WidthRequest = 60;
			this.SteamFolderTN.CanFocus = true;
			this.SteamFolderTN.Name = "SteamFolderTN";
			this.SteamFolderTN.UseUnderline = true;
			global::Gtk.Image w5 = new global::Gtk.Image();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-directory", global::Gtk.IconSize.Menu);
			this.SteamFolderTN.Image = w5;
			this.hbox2.Add(this.SteamFolderTN);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.SteamFolderTN]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(5));
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GameFolderLabel = new global::Gtk.Label();
			this.GameFolderLabel.WidthRequest = 80;
			this.GameFolderLabel.Name = "GameFolderLabel";
			this.GameFolderLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Game folder");
			this.hbox3.Add(this.GameFolderLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GameFolderLabel]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GameFolderBox = new global::Gtk.Entry();
			this.GameFolderBox.CanFocus = true;
			this.GameFolderBox.Name = "GameFolderBox";
			this.GameFolderBox.IsEditable = true;
			this.GameFolderBox.InvisibleChar = '●';
			this.hbox3.Add(this.GameFolderBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GameFolderBox]));
			w9.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GameFolderBtn = new global::Gtk.Button();
			this.GameFolderBtn.WidthRequest = 60;
			this.GameFolderBtn.CanFocus = true;
			this.GameFolderBtn.Name = "GameFolderBtn";
			this.GameFolderBtn.UseUnderline = true;
			global::Gtk.Image w10 = new global::Gtk.Image();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-directory", global::Gtk.IconSize.Menu);
			this.GameFolderBtn.Image = w10;
			this.hbox3.Add(this.GameFolderBtn);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GameFolderBtn]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(5));
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GogLabel = new global::Gtk.Label();
			this.GogLabel.WidthRequest = 80;
			this.GogLabel.Name = "GogLabel";
			this.GogLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Is GOG");
			this.hbox4.Add(this.GogLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GogLabel]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GogBox = new global::Gtk.Entry();
			this.GogBox.CanFocus = true;
			this.GogBox.Name = "GogBox";
			this.GogBox.Text = global::Mono.Unix.Catalog.GetString("False");
			this.GogBox.IsEditable = true;
			this.GogBox.InvisibleChar = '●';
			this.hbox4.Add(this.GogBox);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GogBox]));
			w14.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GogCBtn = new global::Gtk.Button();
			this.GogCBtn.WidthRequest = 60;
			this.GogCBtn.CanFocus = true;
			this.GogCBtn.Name = "GogCBtn";
			this.GogCBtn.UseUnderline = true;
			this.GogCBtn.Label = global::Mono.Unix.Catalog.GetString("change");
			this.hbox4.Add(this.GogCBtn);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GogCBtn]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			w15.Padding = ((uint)(5));
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.LanguageLabel = new global::Gtk.Label();
			this.LanguageLabel.WidthRequest = 80;
			this.LanguageLabel.Name = "LanguageLabel";
			this.LanguageLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Language");
			this.hbox7.Add(this.LanguageLabel);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.LanguageLabel]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.LanguageBox = global::Gtk.ComboBox.NewText();
			this.LanguageBox.WidthRequest = 600;
			this.LanguageBox.Name = "LanguageBox";
			this.hbox7.Add(this.LanguageBox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.LanguageBox]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox2.Add(this.hbox7);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
			w19.Position = 5;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
			w20.Position = 6;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ModSettings = new global::Gtk.Label();
			this.ModSettings.Name = "ModSettings";
			this.ModSettings.Ypad = 6;
			this.ModSettings.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Mod Settings</b>");
			this.ModSettings.UseMarkup = true;
			this.vbox2.Add(this.ModSettings);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.ModSettings]));
			w21.Position = 7;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.vbox2.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator3]));
			w22.Position = 8;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.overwriteButton = new global::Gtk.CheckButton();
			this.overwriteButton.CanFocus = true;
			this.overwriteButton.Name = "overwriteButton";
			this.overwriteButton.Label = global::Mono.Unix.Catalog.GetString("Overwrite Game Files");
			this.overwriteButton.DrawIndicator = true;
			this.overwriteButton.UseUnderline = true;
			this.hbox6.Add(this.overwriteButton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.overwriteButton]));
			w23.Position = 0;
			w23.Fill = false;
			this.vbox2.Add(this.hbox6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
			w24.Position = 9;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator();
			this.hseparator4.Name = "hseparator4";
			this.vbox2.Add(this.hseparator4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator4]));
			w25.Position = 10;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.SteamSettings = new global::Gtk.Label();
			this.SteamSettings.Name = "SteamSettings";
			this.SteamSettings.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Steam Settings</b>");
			this.SteamSettings.UseMarkup = true;
			this.vbox2.Add(this.SteamSettings);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.SteamSettings]));
			w26.Position = 11;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.vbox2.Add(this.hseparator5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator5]));
			w27.Position = 12;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.vbox2.Add(this.hbuttonbox2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
			w28.Position = 13;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.SetVDF = new global::Gtk.Button();
			this.SetVDF.CanFocus = true;
			this.SetVDF.Name = "SetVDF";
			this.SetVDF.UseUnderline = true;
			this.SetVDF.Label = global::Mono.Unix.Catalog.GetString("Set LaunchOptions");
			this.hbox1.Add(this.SetVDF);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.SetVDF]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w30.Position = 14;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.Save = new global::Gtk.Button();
			this.Save.WidthRequest = 60;
			this.Save.CanFocus = true;
			this.Save.Name = "Save";
			this.Save.UseUnderline = true;
			this.Save.Label = global::Mono.Unix.Catalog.GetString("Save");
			this.hbox5.Add(this.Save);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Save]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			w31.Padding = ((uint)(5));
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w32.PackType = ((global::Gtk.PackType)(1));
			w32.Position = 15;
			w32.Expand = false;
			w32.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 740;
			this.DefaultHeight = 447;
			this.Show();
			this.SteamFolderTN.Clicked += new global::System.EventHandler(this.OnSteamFolderTNClicked);
			this.GameFolderBtn.Clicked += new global::System.EventHandler(this.OnGameFolderBtnClicked);
			this.GogCBtn.Clicked += new global::System.EventHandler(this.OnGogCBtnClicked);
			this.SetVDF.Clicked += new global::System.EventHandler(this.OnSetVDFClicked);
			this.Save.Clicked += new global::System.EventHandler(this.OnSaveClicked);
		}
	}
}
