
// This file has been generated by the GUI designer. Do not modify.
namespace SDVMMR
{
	public partial class ErrorAlert
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView ErrorOutput;

		private global::Gtk.Label Message;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Button OKButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SDVMMR.ErrorAlert
			this.CanFocus = true;
			this.Name = "SDVMMR.ErrorAlert";
			this.Title = global::Mono.Unix.Catalog.GetString("Error");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child SDVMMR.ErrorAlert.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(10));
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ErrorOutput = new global::Gtk.TextView();
			this.ErrorOutput.CanFocus = true;
			this.ErrorOutput.Name = "ErrorOutput";
			this.ErrorOutput.Editable = false;
			this.ErrorOutput.CursorVisible = false;
			this.ErrorOutput.AcceptsTab = false;
			this.GtkScrolledWindow.Add(this.ErrorOutput);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.Message = new global::Gtk.Label();
			this.Message.Name = "Message";
			this.Message.LabelProp = global::Mono.Unix.Catalog.GetString("SDVMM Will Now Close");
			this.vbox3.Add(this.Message);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.Message]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(40));
			this.alignment5.RightPadding = ((uint)(40));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.OKButton = new global::Gtk.Button();
			this.OKButton.CanFocus = true;
			this.OKButton.Name = "OKButton";
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = global::Mono.Unix.Catalog.GetString("OK");
			this.alignment5.Add(this.OKButton);
			this.vbox3.Add(this.alignment5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment5]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
